### ISSUE TITLE
Not Working for Theme "Front"

### ISSUE THREAD

**Issue by Instahyper** [nielslange/smntcs-custom-logo-link#114]
I can set up a new link in the customizer, but the settings dont take affect on the site.

FrontVersion: 1.1.20
Von MadrasThemes
(https://themeforest.net/user/madrasthemes/)

**Comment by nielslange** [comment]
Hello @Instahyper 👋

Thank you for reaching out, and I apologize for the delayed response. Unfortunately, I'm unable to provide support for premium themes, as I don't have access to the theme in question. I've shared more details about this in a post on the WordPress support forum [here](https://wordpress.org/support/topic/support-for-themeforest-themes/). 

Since you purchased your theme from [ThemeForest](https://themeforest.net/item/front-multipurpose-business-wordpress-theme/25428980), I recommend contacting the theme developers directly. They may be able to include the feature you're asking about in a future update or offer custom code to meet your needs.

As there's nothing I can do to assist further in this case, I will close this issue. However, please feel free to create a new issue if you have any other questions or need assistance with one of the open-source themes available on [WordPress.org](https://wordpress.org/themes/).
