### ISSUE TITLE
Add theme compatibility

### ISSUE THREAD

**Issue by dialeinpiz** [nielslange/smntcs-custom-logo-link#7]
Hello
I have an issue on the site I'm building and I've tried downloading your plugin, which is unfortunately not working on the cuisine theme.
Could you please add it to your list? That would be much appreciated, thanks a lot in advance.

https://themeforest.net/item/cuisine-responsive-restaurant-wordpress-theme/15683899

**Comment by nielslange** [comment]
Hello @dialeinpiz 👋 As the Cuisine theme is a premium theme, I unfortunately don't have access to it. That said, I should be able to extend my plugin blindly based on the theme demo page on https://preview.themeforest.net/item/cuisine-responsive-restaurant-wordpress-theme/full_screen_preview/15683899. I'll do this right away! 😁

**Comment by nielslange** [comment]
Hello @dialeinpiz, I just created a new version with compatibility to the Cuisine theme. As the Cuisine theme is a premium theme and I don't have access to it, would you mind testing if the updated version works as expected? You can download the updated version via https://github.com/nielslange/smntcs-custom-logo-link/archive/update/%237.zip 

To test the updated version, please make sure to delete the current version from your site as you would receive a `Destination folder already exists` error message otherwise.

**Comment by dialeinpiz** [comment]
You're super fast @nielslange !! Thank you so much for it! I am trying your solution right now and I will let you know shortly.
Thanks in advance for your super fast reaction!

**Comment by dialeinpiz** [comment]
Ooooh it works!!! You are an angel in my day @nielslange thank you so much for your huuuuge help!!!!!

**Comment by nielslange** [comment]
Sweet! Glad that it works as expected, @dialeinpiz! I'll release this version within the next minutes. Oh, and if you like to, feel free to leave a review on https://wordpress.org/plugins/smntcs-custom-logo-link/#reviews. Only if you like to, though! 😁

> Ooooh it works!!! You are an angel in my day @nielslange thank you so much for your huuuuge help!!!!!

You know, due to the current situation I can't go anywhere and helping others is the least thing I can do these days. Stay safe wherever you are! 🙌

**Comment by dialeinpiz** [comment]
It's been a pleasure for me to give you a good review, your huge and fast help has been very much appreciated @nielslange!!
Spending time at home it's really hard, I know. But you should be proud to give smiles to people all over the world. Stay safe you too my friend!
