### ISSUE TITLE
Fix mobile support for the Astra theme

### ISSUE THREAD

**Issue by asleighorlick** [nielslange/smntcs-custom-logo-link#79]
See https://www.loom.com/share/439c1db5d1374fd3a578de3fc01eea4a

**Comment by asleighorlick** [comment]
https://www.loom.com/share/439c1db5d1374fd3a578de3fc01eea4a

**Comment by nielslange** [comment]
Hello @asleighorlick 👋

Thanks for reaching out, and apologies for my delayed response. I looked into this problem and noticed that the Astra theme is using two link locations, one for desktop and one for mobile. I wasn't aware of that initially, but updated this plugin so that it fully supports the Astra theme.
